version: '3.9'
services:
  postgres:
    image: postgres
    container_name: PostgresDB
    restart: always
    volumes:
      - ./src/app/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"